// src/app/terms/page.tsx
"use client";

import {useEffect, useMemo} from 'react';

import {Card, CardContent, CardHeader, CardTitle} from '@/components/ui/card';
import {useTranslations} from '@/lib/i18n';

type TermsSection = {
    title?: string;
    paragraphs?: string[];
    list?: string[];
};

type TermsContent = {
    pageTitle?: string;
    heading?: string;
    sections?: TermsSection[];
};

const emptyTerms: TermsContent = {pageTitle: '', heading: '', sections: []};

export default function TermsPage() {
    const {t} = useTranslations();
    const terms = useMemo(() => (t('terms') as TermsContent | undefined) ?? emptyTerms, [t]);
    const sections = terms.sections ?? [];

    useEffect(() => {
        if (terms.pageTitle) {
            document.title = terms.pageTitle;
        }
    }, [terms.pageTitle]);

    return (
        <div className="blur-background relative min-h-screen bg-background/90">
            <div className="container mx-auto flex min-h-screen items-center justify-center px-4 py-16">
                <Card className="w-full max-w-3xl border border-border bg-card/90 backdrop-blur shadow-xl">
                    <CardHeader className="flex flex-row items-center justify-between">
                        <img alt={String((t('logos.atsAlt') as string) ?? 'ATS')} className="w-24"
                             src="/images/ats-logo.png"/>
                        <img alt={String((t('logos.opnsenseAlt') as string) ?? 'OPNsense')} className="w-32"
                             src="/images/opnsense.png"/>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <CardTitle className="text-2xl font-medium text-foreground">{terms.heading}</CardTitle>
                        <div className="space-y-6 text-sm leading-6 text-muted-foreground">
                            {sections.map((section, index) => (
                                <section key={section.title ?? `section-${index}`} className="space-y-3">
                                    {section.title ?
                                        <h2 className="text-lg font-semibold text-foreground">{section.title}</h2> : null}
                                    {section.paragraphs?.map((paragraph, paragraphIndex) => (
                                        <p key={`${section.title ?? 'paragraph'}-${paragraphIndex}`}>{paragraph}</p>
                                    ))}
                                    {section.list ? (
                                        <ol className="list-decimal space-y-2 pl-5">
                                            {section.list.map((item, itemIndex) => (
                                                <li key={`${section.title ?? 'item'}-${itemIndex}`}>{item}</li>
                                            ))}
                                        </ol>
                                    ) : null}
                                </section>
                            ))}
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}

// src/routes/terms/+page.svelte
<script lang="ts">
    import {t} from '$lib/i18n';

    interface TermsSection {
        title?: string;
        paragraphs?: string[];
        list?: string[];
    }

    interface TermsContent {
        pageTitle?: string;
        heading?: string;
        sections?: TermsSection[];
    }

    const emptyTerms: TermsContent = {pageTitle: '', heading: '', sections: []};

    $: terms = ($t('terms') as TermsContent | undefined) ?? emptyTerms;
    $: sections = terms.sections ?? [];
</script>

<svelte:head>
    <title>{terms.pageTitle}</title>
</svelte:head>

<div class="blur-background relative min-h-screen bg-gray-100">
    <div class="container mx-auto max-w-2xl p-5 min-h-screen flex items-center justify-center">
        <div class="bg-white shadow-lg rounded-lg px-8 pt-6 pb-8 mb-4">
            <div class="flex justify-between items-center mb-6">
                <img alt={$t('logos.atsAlt')} class="w-24" src="/images/ats-logo.png"/>
                <img alt={$t('logos.opnsenseAlt')} class="w-32 justify-end" src="/images/opnsense.png"/>
            </div>

            <header class="mb-10">
                <div class="prose">
                    <h1 class="text-2xl font-medium mb-4">{terms.heading}</h1>

                    {#each sections as section (section.title)}
                        <div class="mb-4">
                            <h2 class="text-xl font-semibold">{section.title}</h2>

                            {#if section.paragraphs}
                                {#each section.paragraphs as paragraph}
                                    <p>{paragraph}</p>
                                {/each}
                            {/if}

                            {#if section.list}
                                <ol class="list-decimal pl-5">
                                    {#each section.list as item}
                                        <li>{item}</li>
                                    {/each}
                                </ol>
                            {/if}
                        </div>
                    {/each}
                </div>
            </header>
        </div>
    </div>
</div>
